Testing `test/e2e/alcotest/failing/check_basic.ml'.
This run has ID `<uuid>'.

ASSERT bool
  [FAIL]        different basic              0   bool.
ASSERT int
  [FAIL]        different basic              1   int.
ASSERT int32
  [FAIL]        different basic              2   int32.
ASSERT int64
  [FAIL]        different basic              3   int64.
ASSERT float
  [FAIL]        different basic              4   float.
ASSERT char
  [FAIL]        different basic              5   char.
ASSERT string
  [FAIL]        different basic              6   string.
ASSERT bytes
  [FAIL]        different basic              7   bytes.
ASSERT list
  [FAIL]        different composite          0   list.
ASSERT array
  [FAIL]        different composite          1   array.
ASSERT option some
  [FAIL]        different composite          2   option some.
ASSERT result
  [FAIL]        different composite          3   result.
ASSERT pair
  [FAIL]        different composite          4   pair.
ASSERT triple
  [FAIL]        different composite          5   triple.

┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different basic              0   bool.                         │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL bool

   Expected: `true'
   Received: `false'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different basic              1   int.                          │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL int

   Expected: `1'
   Received: `2'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different basic              2   int32.                        │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL int32

   Expected: `2147483647'
   Received: `-2147483648'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different basic              3   int64.                        │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL int64

   Expected: `9223372036854775807'
   Received: `-9223372036854775808'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different basic              4   float.                        │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL float

   Expected: `1'
   Received: `2'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different basic              5   char.                         │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL char

   Expected: `'a''
   Received: `'b''

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different basic              6   string.                       │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL string

   Expected: `"Lorem ipsum"'
   Received: `"dolor sit amet."'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different basic              7   bytes.                        │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL bytes

   Expected: `"\001\002\003"'
   Received: `"\001\000\003"'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different composite          0   list.                         │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL list

   Expected: `['a'; 'b']'
   Received: `['a'; 'c']'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different composite          1   array.                        │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL array

   Expected: `[|0; 9223372036854775807|]'
   Received: `[|0; 1; 9223372036854775807|]'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different composite          2   option some.                  │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL option some

   Expected: `Some 1'
   Received: `Some 2'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different composite          3   result.                       │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL result

   Expected: `Ok 1'
   Received: `Error ()'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different composite          4   pair.                         │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL pair

   Expected: `(1, 'a')'
   Received: `(1, 'b')'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────


┌──────────────────────────────────────────────────────────────────────────────┐
│ [FAIL]        different composite          5   triple.                       │
└──────────────────────────────────────────────────────────────────────────────┘
FAIL triple

   Expected: `(1, true, "a")'
   Received: `(1, false, "a")'

Raised at <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__
Called from <exception-name> in file "<file-name>", line __-__, characters __-__

 ──────────────────────────────────────────────────────────────────────────────

14 failures! in <test-duration>s. 14 tests run.
